= IP Whitelist Policy

The IP Whitelist policy allows you to create an explicit list of IPs that can access your deployed endpoints. IP addresses that aren't on this white list are rejected. 

If you have an IP Whitelist policy assigned, you need to whitelist all IP addresses that are coming through your exposed endpoint.

IP Whitelist policy violations escalate to authentication errors for the DoS policy.

[NOTE]
This source is IP based. If an attacker can spoof his source IP address, these measures cannot prevent the attack.

== Differences with API Gateway Policies

The IP Whitelist policy is a list of all IP addresses allowed to connect to your endpoint, and this whitelist applies to all applications. You can set up an API Gateway Whitelist policy per API list.

=== Example

You can set up an IP Whitelist policy to allow `a.a.a.a`, `y.y.y.y`, and `z.z.z.z`. +
Then, API-1 (`/api1`) uses an API Whitelist policy that allows `x.x.x.x`, and API-2 (`/api2`) uses another policy that allows `y.y.y.y` and `z.z.z.z`.

* IP Address `w.w.w.w` is rejected by both APIs, because it's not whitelisted at the IP Whitelist policy.
* IP Address `y.y.y.y` requesting `/api1`, is allowed at the IP Whitelist policy level, and rejected by the API Whitelist policy at `/api1`.
* IP Address `y.y.y.y` requestion `/api2`, is allowed at the IP Whitelist policy level, and allowed by the API Whitelist policy at `/api2`.

== Configure IP Whitelist Policy

. Navigate to *Anypoint Security*, click *Create Policy*, and select *IP Whitelist*.
. Add a name for your policy in the *Name* field.
. Under *IP White List*, click *Add IP*.
. Insert the range of IP addresses to whitelist. You must use the CIDR format for a range of IP addresses. +
For example, using the IP address 10.111.0.0/24, whitelists the addresses from `10.111.0.0` to `10.111.0.254`. +
To add more ranges of IP address, click *Add IP* again.
. Click *Save Policy*.

== Manage Blocked IP Addresses

You can log a list of blocked IP addresses and unblock IP addresses in Runtime Fabric. Make sure you verify that all issues that caused the IP address to be blocked are resolved before you unblock the IP address. 

. In Anypoint Platform go to *Management Center > Runtime Manager*.
. In the left navigation menu, click *Runtime Fabrics*.  
. Select the Runtime Fabric to manage the blocked IP addresses for. 
. Select the *Inbound Traffic* tab. 
. In the *Security Policies* section, click *Manage blocked IPs*.
. In the *Manage blocked IPs* dialog box, you can download a list of blocked IP addresses into a log file or unblock IP addresses. 

== Unblock Blocked IP Addresses

. To unblock IP addresses, enter the IP addresses to unblock in the field, then click *Unblock IPs*. +
. In the *Unblock an IP Address* field, enter an individual or a range of IP addresses. +
For example, to unblock a range of IP addresses, enter: `192.0.2.0–192.0.2.255` +
When the IP addresses are successfully unblocked, an `Unblocked` message displays.

== Log Blocked IP Addresses

. To generate a list of blocked IP addresses, click *Log blocked IPs*. +
When the blocked IP addresses are successfully logged, a `Logged` message appears. 

== See Also

* xref:api-manager::ip-whitelist.adoc[IP Whitelist]
* xref:cap-policy.adoc[HTTP Limits Policy]
* xref:dos-policy.adoc[DoS Policy]
