//COMMENT about test of proposed method: One downside is that I cannot see what has changed and what has not. There are no colors, and I cannot flip back and forth using the back and forward arrows without losing edits. I essentially have to keep two files open.//


= Create a Secret Group (Anypoint Platform)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


== Prerequisites

* Verify that you have the `Write secrets` permission enabled. 
* Verify that you are in the correct environment using the environment switcher at the top of the left navigation bar.

== Create a Secret Group

. In Anypoint Platform, go to Management Center and select *Secrets Manager*.
. Click *Create Secret Group*.
. Type a name for the secret group and click *Save*.
+
The name of your secret group must: 
+
* Be at least three characters long and no longer than 35 characters
* Start with a letter
* Contain only letters, numbers, and dashes (but cannot end with a dash)

//BEGIN EDIT//

The secret group appears in the *Secret Groups* list view. Click *Edit* to add the necessary secret types, such as a certificate, keystore, or truststore.

//"Click *Edit* to add..." is misleading, because none of the following ADD topics begins with clicking *Edit*. Clarify.
Suggest instead something like "After creating your secret group, it appears in the Secret Groups list view. You can then add the necessary secret types by adding a truststore or a keystore."//

//Are certificate, keystore, and truststore the "necessary secret types," or do they CONTAIN the secret types? Clarify. 
Be sure to list them in the same order in which they appear below, and clarify whether "certificate" corresponds to "Add a Certificate Pinset."//

//Also, what about introducing the other things that you can add after creating the truststore? We should prepare the audience for each of the == tasks that follows CREATE a truststore.
Should they in fact be subtopics to CREATE?//

//Question: Are these == topics presented here in the order in which a user would need them? 
After CREATE a trust store, does the user next have to EDIT the trust store in order to ADD the items covered in the ADD topics?//

//END EDIT//

== Add a Truststore

Add a truststore for public certificates of trusted servers. The truststore is stores up to 15 certificates from the trusted CA, which are then used to verify certificates presented by the server in an SSL connection.

. In the Secret Groups list view, select the secret group to receive a new truststore. 
. Select *Truststore* in the menu on the left, and click *Add Truststore*. 
. In the *Add Truststore* screen, add the required information. 
+
* *Name* - Enter a name for your keystore.
* *Type* - Select the truststore type from the drop-down menu. +
Supported types are:
+
** PEM
** JKS
** PKCS12
** JCEKS
* *Truststore File* - Click *Choose File*, and select the truststore file to upload. 
* *Override Expiration Date* (Optional) - Select the date to override the default expiration date of the certificate. +
[NOTE]
If you are uploading a JKS, PKCS12, or JCEKS truststore file, you must also provide the passphrase for this truststore.
. Click *Save*.

[[add_keystore]]
== Add a Keystore

Specify the type of keystore to add to the secret group. The keystore is the combination of the authorization certificate, its corresponding private keys, and the certification authority's path.

. In the *Secret Groups* list view, select the secret group to which to add a keystore. 
. Select *Keystore* in the menu on the left, and click *Add Keystore*. 
. In the *Name* field, enter a name for your keystore.
. In the *Type* field, select the keystore type from the drop-down menu.
+
Supported types include:
+
* Privacy Enhanced Mail (PEM) - Base64 encoded ASCII file with a `cer`, `crt`, or `pem` extension.
* Java Keystore (JKS) - Repository for authorization or public key certificates. The JKS keystore type does not store secret keys.
* PKCS12 - Stores server and intermediate certificates in an archive file format. The PKCS12 keystore type does not store secret keys.
* Java Cryptography Extension KeyStore (JCEKS) - Stores server and intermediate certificates as well as secret keys.
.. To add a *PEM* type keystore, you must provide: 
+
** *Certificate File* - Click *Choose File* to locate and upload the PEM certificate file.  
** *Key File* - Click *Choose File* to locate and upload the PEM formatted file that contains the private key for the certificate. 
** *Key Passphrase* - Enter the word or phrase that protects the private key. 
** *CA Path Certificate File* (Optional) - Click *Choose File* to locate and upload the certificate signed by a certification authority (CA). +
The CA path contains the intermediary and root certificates that are related to the certificate file you want to use.    
** *Override Expiration Date* (Optional) - Select the date to override the default expiration date of the certificate.
.. To add a *JKS*, *PKCS12*, or *JCEKS* type keystore, you must provide: 
+
** *Keystore File* - Click *Choose File* to locate and upload the keystore file to use.
** *Keystore Passphrase* - Enter the word or phrase that protects the keystore.
** *Alias* - The alias used to access the keystore entries (key and trusted certificate entries).
** *Key Passphrase* - The word or phrase that protects the private key.
** *Algorithm* (Optional) - The algorithm to use for encryption of keys.
** *Override Expiration Date* (Optional) - Select the date to override the default expiration date of the certificate.
. Click *Save*.

== Add a Certificate Pinset

Add a concatenated list of PEM certificates to the secret group. 

. In the *Secret Groups* list view, select the secret group to which to add a certificate pinset. 
. Select *Certificate Pinset* in the menu on the left, and click *Add Certificate Pinset*. 
. In the *Certificate Pinset* screen, add the required information. +
* *Name* - Enter a name for the certificate pinset. 
* *Certificate File* - Click *Choose File* and select the PEM formatted CA certificate to upload.
* *Expiration Date* (Optional) - Select the expiration date for the certificate.

== Add a Shared Secret

Add a shared secret users can use for authentication. 

. In the *Secret Groups* list view, select the secret group to which to add a shared secret. 
. Select *Shared Secret* in the menu on the left, and click *Add Shared Secret*. 
. In the *Add Shared Secret* screen, add the required information. 
+
* *Name* - Enter a name for your shared secret.
* *Type* - Select the shared secret type from the drop-down menu.
 ** *Username Password* - Provide a username and password.
 ** *Symmetric Key* - Provide a Base64 string containing symmetric key.
 ** *S3 Credential* - Provide the access key ID and the secret access key to an S3 bucket.
 ** *Blob* - Provide a base64-encoded value.
. Click *Save*. 

== Add a List of Revoked Certificates 

Add a list of certificates that were revoked by certificate authorities before their expiration dates. The server administrator (owner of Edge) may specify a CRL list and other algorithms to retrieve this list, or the server owner may point to an external public key infrastructure (PKI) or another vendor that maintains a list of revoked certificates. 

. In the *Secret Groups* list view, select the secret group to which to add a Certificate List Distributor (CRL) configuration. 
. In the menu on the left side, select *CRL Distributor Config*, and click *Add CRL*. 
. In the *Add Certificate Revocation List (CRL) Distributor Config* screen, add the required information.
+
* *Name* - Enter a name for your CRL distribution point.
* *Distributor Certificate* - Select the CRL distributor from the drop-down list.
//_COMBAK: How to populate this drop-down. 
* *CA Certificate* - select the CA certificate to query against the CRL distributor from the drop-down list. 
//_COMBAK: This can be a URL, FTP, and LDAP?
* *Frequency (in minutes)* - Determine the interval (in minutes) to query the CRL distributor.
* *Complete CRL Issuer URL* - Add the URL for all of the revoked certificates.
* *Delta CRL Issuer URL* (Optional) - Add the URL for the list of all certificates revoked since the last time a complete CRL was created. 
* *Expiration Date* (Optional) - Select the expiration date for the certificate.
. Click *Save*.

== Edit a Secret Group

When you edit a secret group, other users are locked out while you edit the necessary security objects.

. In Secrets Manager, click *Edit* for the secret group that you want to update. 
. Make your changes and click *Finish*. +
The secret group is updated with the changes, and Secrets Manager serves the updated secrets to all redeployed applications after this point. 

//I am confused by the following step: FINISH does not end the edit session? 
If you finish your edits, do you still have to go to the next step to close the session?
*Cancel Edit* sounds like something you would only use to end an unfinished edit.
CLARIFY that a user must do both, if that is true.//

. Click *Cancel Edit* to close your open edit session. +
This makes the *Edit* button available so you can make updates to the secret group. +

//But why would you do this rather than continuing to edit/make updates to the secret group?//

You can also take this step to cancel another user's open and abandoned editing session, so that you or other users can open your own editing sessions. This deletes all the changes made by the user who abandoned the editing session. +



== See Also

* xref:secret-group-add-tls-context.adoc[Add a TLS Context]
* xref:asm-permission-concept.adoc[Secrets Manager Permissions]
* xref:asm-secret-type-support-reference.adoc[Supported Secret Types Reference]
* xref:runtime-fabric::enable-inbound-traffic.adoc[Enable Inbound Traffic on Anypoint Runtime Fabric]
x xref:api-manager::building-https-proxy[Build an HTTPS API Proxy]

