= Create and Edit Secret Group (Anypoint Platform)

Secrets Manager enables you to create and edit secrets groups, which is a logical grouping of secrets. Secrets Manager also enables you to create new secret types and add them to a secrets group.

== Prerequisites

To create and edit secret groups:

* Verify that you have the `Write secrets` permission enabled. 
* Verify that you are in the correct environment using the environment or business group.

== Create a Secret Group

. In Anypoint Platform, go to Management Center then select *Secrets Manager*.
. Click *Create Secret Group*.
. Enter a name for the secret group and click *Save*.
+
The name of your secret group must: 
+
* Start with a letter
* Be at least three characters long and no longer than 35 characters
* Contain only letters, numbers, and dashes; however, the name cannot end with a dash.

After creating your secret group, it appears in the *Secret Groups* list view. You can continue to add the necessary secret types or add these features later by editing the secret group.

[[add_keystore]]

To add secret types, follow these tutorials:

* xref:secret-group-add-keystore.adoc[Add a Keystore]
* xref:secret-group-add-truststore.adoc[Add a Truststore]
* xref:secret-group-add-certificate.adoc[Add a Certificate]
* xref:secret-group-add-certificate-pinset.adoc[Add a Certificate Pinset]
* xref:secret-group-add-shared-secret.adoc[Add a Shared Secret]
* xref:secret-group-add-tls-context.adoc[Add a TLS Context for Mule]
* xref:configure-tls-context-rtf-lb.adoc[Add a TLS Context for Runtime Fabric Load Balancer]

If you add these secret types when creating your secret group, you do not need to follow the edit step.

== Edit a Secret Group

To edit a secrets group to add secret types:

. Go to *Anypoint Platform > API Manager*.
. In the *Secret Groups* list view, select the secret group you want to edit, then click *Edit*. 
. Make changes to the secrets as required.

As you create or save changes to a secret, the changes are applied immediately. The updated secret group is immediately available the next time the secret group is accessed or when deploying an application.





////
== Add a List of Revoked Certificates 

A Certificate Revocation List (CRL) distributor is an entity that creates and maintains a list of certificates issued by the CA that are no longer trusted because their associated private keys, or a signing CA, were compromised.

The secrets manager enables you to create CRL distribution points to query a CRL distributor for a specific CA certificate. 
To configure a CRL distributor, you must provide the URL of the CRL distributor, a CA certificate, and a frequency to check the list for updates. +
Because some CRL lists can grow very large, you can provide an optional Delta CRL issuer URL (if the CRL distributor supports it) to retrieve deltas to the CRL list, instead of retrieving the entire list.

Add a list of certificates that were revoked by certificate authorities before their expiration dates. The server administrator may specify a CRL list and other algorithms to retrieve this list, or the server owner may point to an external public key infrastructure (PKI) or another vendor that maintains a list of revoked certificates. 

. In the *Secret Groups* list view, select the secret group to which to add a Certificate List Distributor (CRL) configuration, and click *Edit*. 
. In the menu on the left side, select *CRL Distributor Config*, and click *Add CRL*. 
. In the *Add Certificate Revocation List (CRL) Distributor Config* screen, add the required information.
+
* *Name* - Enter a name for your CRL distribution point.
* *Distributor Certificate* - Select the CRL distributor from the drop-down list.
//_COMBAK: How to populate this drop-down. 
* *CA Certificate* - select the CA certificate to query against the CRL distributor from the drop-down list. 
//_COMBAK: This can be a URL, FTP, and LDAP?
* *Frequency (in minutes)* - Determine the interval (in minutes) to query the CRL distributor.
* *Complete CRL Issuer URL* - Add the URL for all of the revoked certificates.
* *Delta CRL Issuer URL* (Optional) - Add the URL for the list of all certificates revoked since the last time a complete CRL was created. 
* *Expiration Date* (Optional) - Select the expiration date for the certificate.
. Click *Save*.
////




== See Also

* xref:secret-group-add-tls-context.adoc[Add a TLS Context]
* xref:asm-permission-concept.adoc[Secrets Manager Permissions]
* xref:asm-secret-type-support-reference.adoc[Supported Secret Types Reference]
* xref:runtime-fabric::enable-inbound-traffic.adoc[Enable Inbound Traffic on Anypoint Runtime Fabric]
x xref:api-manager::building-https-proxy[Build an HTTPS API Proxy]
