= Supported Secret Types Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Simple Secret Types

[%header%autowidth.spread,cols="a,a"]
|===
| Secret Type | Description
| Shared Secret
| This security object contains a username and password or a base64-encoded symmetric key. +
The shared secret is used for symmetric encryption and decryption, where the secret is known by both the message sender and the message recipient. The sender uses the key to encrypt and sign the message. The recipient uses the key to decrypt the message and verify a message’s digital signature.

The secrets manager allows an administrator to define either a static username and password combination, a static symmetric key, S3 bucket, or blobs.

| Certificate
| This security object contains an X.509 certificate and an electronic document that uses a digital signature to bind a public key with an identity. +
The secrets manager supports PEM and JKS certificates.
|===

== Secret Types Used in TLS and SSL Communication

[%header%autowidth.spread,cols="a,a"]
|===
| Secret Type | Description
| Keystore
|  A Keystore is a repository of security certificates (either authorization certificates or public key certificates), plus corresponding private keys used, for example, in SSL encryption. +
Supported keystore types are:

* JKS
* JCEKS
* PEM
* PKCS12

| Truststore
| A truststore is a repository of security certificates from other parties with which you expect to communicate, or from Certificate Authorities that you trust to identify other parties. +
The secrets manager truststore accepts the following standard format inputs:

* PEM
* JKS
* PKCS12
* JCEKS

| Certificate Pinset
| A Certificate Pinset is a repository of security certificates from other parties that associate a client or host with their expected X.509 certificate or public key. These security certificate identities are then "pinned" to clients or hosts. +
This repository or "Pin Set" acts as a white list of certificates that can be used, for example, to identify clients in a SSL/TLS connection. The secrets manager will accept a concatenated list of PEM certificates as input.

| TLS Context
| This security object defines all SSL critical security parameters.
|===

[[tls_support_rtf]]
== TLS Support on Anypoint Runtime Fabric

OpenSSL 1.1.1 and TLS 1.3 provide the following security enhancements and performance improvements over TLS 1.2:

* 2x or greater TLS 1.2 connection performance throughput boost versus prior Runtime Fabric internal load balancer running on OpenSSL 1.0.2
* Reduction of one round trip in full handshake for TLS 1.3 vs. TLS 1.2
* Added TLS 1.2 and TLS 1.3 ChaCha20-Poly1305 ciphers for better mobile and IoT device support
* TLS 1.3 protection against downgrade attacks
* Continued support for both RSA and ECDSA keys
* TLS 1.3 removes obsolete and insecure features from TLS 1.2 and TLS 1.1. +
See xref:release-notes::anypoint-security/anypoint-security-rtf-edge.adoc[Anypoint Security Edge Release Notes] for a list of supported and deprecated ciphers.

The TLS 1.3 protocol is enabled by default for those clients that support it.

== See Also

* xref:index-secrets-manager.adoc[Secrets Manager]
* xref:asm-secret-group-concept.adoc[Secret Groups]
* xref:asm-permission-concept.adoc[Secrets Manager Permissions]
