= Content Attack Prevention Policy

The Content Attack Prevenetion (CAP) policy prevents an attacker to take up all your bandwith by sending large messages. +
This policy checks TCP protocol message sizes and headers. This policy does not check content.

The default allowed message size is large. You need to tune the message size allowed by your policy based on your application needs. +
It's recommended to set up size limits with which all of your APIs can handle.

This policy applies to all your APIs behind your Edge/Ingress endpoint. You can apply API Gateway policies to each API to enforce other API specific policies, such as throttling, JSON Threat Protection.

== Configuring CAP Policy

. Navigate to *Anypoint Security*, click the *Create Policy* icon, and select *Content Attack Prevention*.
. Add a name for your policy in the *Name* field.
. Configure the maximum sizes for message, path header and trailers in the fields below:
+
[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
|*Maximum Message Size* | Maximum tolerated message size, in bytes, for your policy.
|*Maximum Path Length* | Maximum tolerated path size, in bytes, for your policy.
|*Maximum Length Of a Single Header* | The maximum tolerated length of a header for your policy.
|*Maximum Length Of a Single Trailer* | The maximum tolerated length of a trailer for your policy.
|*Maximum Number Of Headers and Trailers* | The maximum number of headers and trailers allowed by your policy.
|===
. If you want to filter specific HTTP methods, configure them in the *Allowed HTTP Request Methods* field. +
Allowed methods are: GET, POST, PATCH, HEAD, TRACE, OPTIONS, DELETE, and PUT.
. Click *Save*.

== See Also

* xref:acl-policy.adoc[ACL Policy]
* xref:dos-policy.adoc[DoS Policy]
