= HTTP Limits Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Security uses the HTTP Limits policy to prevent an attacker from sending large messages that can consume bandwidth and result performance degradation or system outage. This policy applies to all the APIs behind your Edge inbound endpoint. You can apply API Gateway policies to each API to enforce other API-specific policies, such as throttling and JSON threat protection.

The HTTP Limits policy limts the size of TCP protocol messages, paths, headers, and footers. This policy does not perform checks on the content of a message.

When you configure a DoS Policy, violations to the HTTP Limits policy escalate as protocol errors.


[[anypoint_security_prereqs]]
== Prerequisites

include::partial$anypoint-security-policies-prereqs.adoc[]

== Configure an HTTP Limits Policy

You can configure and apply an HTTP Limits policy to increase or decrease default HTTP limits. 

. Navigate to *Anypoint Security*, click the *Create Policy* icon, and select *Content Attack Prevention*.
. Add a name for your policy in the *Name* field.
. Configure the following parameters for your policy:
+
[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
|*Maximum Message Size* a| The default maximum message size allowed is 104857600 bytes. +
Modify this value based on the requirements of your application by setting the maximum size to a value based on a size your APIs can handle. +
If the request body scanning option is enabled, do not set this value to a value larger than required to prevent attackers from abusing request body checking and exhausting resources.
 
|*Maximum Path Length* | The default maximum path length is 4096 bytes. The range of values is between 256 bytes and 64 kilobytes.
|*Maximum Length Of a Single Header* | The default maximum header length is 16384 bytes. The range of possible values is between 256 bytes and 64 kilobytes.
|*Maximum Length Of a Single Trailer* | The default maximum trailer length is 16384 bytes. The range of possible values is between 256 bytes and 64 kilobytes.
|*Maximum Number Of Headers and Trailers* | The default maximum number of headers and trailers allowed is 32 kilobytes.
|===

. To allow only specific HTTP methods, add them in the *Allowed HTTP Request Methods* field.
+
Valid HTTP methods are: GET, POST, PATCH, HEAD, TRACE, OPTIONS, DELETE, and PUT.
. Click *Save Policy*.

== See Also

* xref:acl-policy.adoc[IP Whitelist Policy]
* xref:dos-policy.adoc[DoS Policy]
* xref:create-waf-policy.adoc[Create a WAF Policy]
