= HTTP Limits Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The HTTP Limits policy prevents an attacker from sending large messages that consume all your bandwidth. +
This policy checks TCP protocol message sizes and headers. This policy does not check content.

This policy applies to all the APIs behind your Edge inbound endpoint. You can apply API Gateway policies to each API to enforce other API specific policies, such as throttling and JSON Threat Protection.

When you configure a DoS policy, violations to the HTTP Limits policy escalate as protocol errors.


[[anypoint_security_prereqs]]
== Prerequisites

include::partial$anypoint-security-policies-prereqs.adoc[]

== Configure an HTTP Limit Policy

You can configure and apply an HTTP Limits policy to increase or decrease default HTTP limits. 

. Navigate to *Anypoint Security*, click the *Create Policy* icon, and select *Content Attack Prevention*.
. Add a name for your policy in the *Name* field.
. Configure the maximum sizes for message, path header and trailers in the fields below:
+
[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
|*Maximum Message Size* a| The default maximum message size allowed is 104857600. If request body scanning is enabled, this value should be set no larger than required to prevent attackers from abusing request body checking and exhausting resources. +
The default allowed message size is large. You need to tune the message size allowed by your policy based on your application needs. +
[NOTE]
Set the size limits to what all of your APIs can handle.

|*Maximum Path Length* | The default maximum path size allowed for your policy is 4096 bytes.
|*Maximum Length Of a Single Header* | The default maximum header length allowed for your policy is 16384 bytes.
|*Maximum Length Of a Single Trailer* | The default maximum trailer length allowed for your policy is 16384 bytes.
|*Maximum Number Of Headers and Trailers* | The default maximum number of headers and trailers allowed by your policy is 32 kB.
|===
. If you want to filter specific HTTP methods, configure them in the *Allowed HTTP Request Methods* field. +
Allowed methods are: GET, POST, PATCH, HEAD, TRACE, OPTIONS, DELETE, and PUT.
. Click *Save Policy*.

== See Also

* xref:acl-policy.adoc[IP Whitelist Policy]
* xref:dos-policy.adoc[DoS Policy]
* xref:create-waf-policy.adoc[Create a WAF Policy]
