= Enable Client Authentication
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you choose a target value of *Anypoint Security* when adding your TLS context, you can optionally enable client authentication. TLS-enabled clients verify that they trust the server by validating the public certificate against their own set of trusted certificates.

To enable client authentication:

. Select *Enable Client Authentication* and provide the following information: +
* *Verification Depth* +
Select the maximum depth to allow for the certificate chain verification.
* *Revocation Method* +
// Select *CRL* to use a certificate revocation list. 
* *Send Trust Store* +
Select this option if you want the edge to send the truststore to the far-end client for mutual TLS.
* *Perform Certificate Pinning* +
Select this option if you want the client to authenticate the server by validating the server's certificate. 
. Click *Advanced Options* to expand the available options, and select the options to enable: +
* *Certificate Checking Strength* +
Allows the application to control whether strict or lax certificate checking is performed during chain-of-trust processing.
* *Certificate Policy Checking* +
Controls certificate policy processing as defined in RFC 3280 and 5280.
A certificate can contain zero or more policies. A policy is represented as an object identifier (OID). In an end entity certificate, this policy information indicates the policy under which the certificate has been issued and the purposes for which the certificate can be used. +
In a CA certificate, this policy information limits the set of policies for certification paths that include this certificate. Applications with specific policy requirements are expected to have a list of those policies that they will accept and to compare the policy OIDs in the certificate to that list. If this extension is critical, the path validation software must be able to interpret this extension (including the optional qualifier), or must reject the certificate.
* *OID* +
Select the object identifier options, which include: +
** *Require Initial Explicit Policy* +
Indicates that the path must be valid for at least one of the certificate policies in the `user-initial-policy-set`.
** *Certificate Policies* +
At minimum, consists of a policy identifier (OID). 
* *Authentication Overrides* +
Select the criteria for when to override failing authentication when mutual authentication is performed. 
. Click *Save*.

== See Also

* xref:configure-tls-context-rtf-lb.adoc[Configure a TLS Context for Runtime Fabric Load Balancer]
* xref:cipher-suites.adoc[Cipher Suites]