= Manage Blocked IP Addresses in Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In a Runtime Fabric with Anypoint Security enabled, you can unblock IP addresses and generate a list of blocked IP addresses, which you can view in Runtime Fabric logs. 

== Prerequisites

To manage blocked IP addresses in Runtime Fabric you must:

* Have a running Runtime Fabric
* Have a xref:dos-policy.adoc[DoS policy configured] and deployed to Runtime Fabric

== Manage Blocked IP Addresses

. In Anypoint Platform go to *Management Center > Runtime Manager*.
. In the left navigation menu, click *Runtime Fabrics*.  
. Select the Runtime Fabric for which to manage the blocked IP addresses. 
. Select the *Inbound Traffic* tab. 
. In the *Security Policies* section, click *Manage blocked IPs*.
. In the *Manage blocked IPs* dialog box, you can download a list of blocked IP addresses into a log file or unblock IP addresses. 

== Unblock IP Addresses

. In the *Manage blocked IPs* dialog, to unblock an IP address or range of IP addresses, enter an IP address and CIDR in the *Unblock an IP Address* field.  +
For example, to unblock a single IP address, enter: `192.0.2.0/32`. +
To unblock a range of IP addresses, enter: `192.0.2.0/24`. 
. Click *Done*. +
When the IP addresses are successfully unblocked, an `Unblocked` message appears.

== Log Blocked IP Addresses

. To generate a list of blocked IP addresses, click *Log blocked IPs*. +
When the blocked IP addresses are successfully logged, a `Logged` message appears. 
. To view the logs, follow the instructions in the xref:runtime-fabric::runtime-fabric-logs.adoc[View and Configure Logging] for configuring log forwarding. +
The logs look similar to this: +

[source,json]
----
{
	"body": [{
		"action": "BlockForever",
		"ip": "172.31.104.239",
		"category": "RoutingError"
	}, {
		"action": "BlockForever",
		"ip": "172.31.104.240",
		"category": "RoutingError"
	}, {
		"action": "BlockForever",
		"ip": "172.31.106.88",
		"category": "RoutingError"
	}, {
		"action": "BlockForever",
		"ip": "172.31.106.89",
		"category": "RoutingError"
	}, {
		"action": "BlockForever",
		"ip": "172.31.106.90",
		"category": "RoutingError"
	}, {
		"action": "BlockForever",
		"ip": "172.31.106.91",
		"category": "RoutingError"
	}, {
		"action": "BlockForever",
		"ip": "172.31.106.92",
		"category": "RoutingError"
	}, {
		"action": "BlockForever",
		"ip": "172.31.106.107",
		"category": "RoutingError"
	}],
	"hdr": {
		"logType": "EdgeJSON",
		"name": "doSActionsView",
		"time:": "2019-03-29 18:38:48"
	}
}
----

== See Also

* xref:1.x@api-manager::ip-whitelist.adoc[]
* xref:cap-policy.adoc[]
* xref:dos-policy.adoc[]
* xref:runtime-fabric::runtime-fabric-logs.adoc[]
