= Add a Truststore
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


Add a truststore for public certificates of trusted servers. The truststore stores up to 15 certificates from the trusted CA, which are then used to verify certificates presented by the server in an SSL connection.

To add a truststore to your secret group:

. In the Secret Groups list view, select the secret group to receive a new truststore, and click *Edit*. 
. Select *Truststore* in the menu on the left, and click *Add Truststore*. 
. In the *Add Truststore* screen, add the required information. 
+
* *Name* +
Enter a name for your truststore.
* *Type* +
Select the truststore type from the drop-down menu. +
Supported types are:
+
** PEM
** JKS
** PKCS12
** JCEKS
* *Truststore File* +
Click *Choose File* and select the truststore file to upload. 
* *Override Expiration Date* +
Select the date to override the default expiration date of the certificate. +
[NOTE]
If you are uploading a JKS, PKCS12, or JCEKS truststore file, you must also provide the passphrase for this truststore.
. Click *Save*.
