= TLS Context
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you create a secret group, you can add a TLS context to encrypt inbound traffic to Runtime Fabric or Mule 4 proxies. 

You can use the TLS context you store in Secrets Manager either when you configure an HTTPS API Proxy, or to validate the SSL handshake in the edge endpoint of Runtime Fabric.

== Add TLS Context 

Add a TLS context to your Secret Group. 

. In the *Secret Groups* list view, select the secret group to which to add a TLS context. 
. Select *TLS Context* in the menu on the left, and click *Add TLS Context*. 
. In the Create TLS Context screen, add the required information.
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select the target for the TLS context from the drop-down list. 
** *Anypoint Security* +
Validates the SSL handshake for Runtime Fabric. +
If you use the *Anypoint Security* target, you can select keystores and truststores that are either PEM or non-PEM types. Supported types include: +
*** JKS
*** PKCS12
*** JCEKS 
** *Mule* +
Uses the TLS context as the SSL validation for Mule 4 based API proxies.
* *TLS Version* +
Select the TLS version. Supported versions include: 
+
[%header%autowidth.spread,cols="a,a"]
|===
|Target |Supported TLS Version
|Mule a| * TLS 1.1
* TLS 1.2

|Anypoint Security a| * TLS 1.1
* TLS 1.2
* TLS 1.3
|===    
* *Keystore* +
Select the keystore to store the TLS context in from the drop-down list.
* *Truststore* +
(Optional) Select a truststore to add the TLS context to from the drop-down list. +
If the target for the TLS Context is Mule, you can select *Insecure* if you don't want certificate validation enforced. 
* *Expiration Date* +
(Optional) Select the expiration date for the certificate.
. Click *Save*.

Additionally, you can enable client authentication and select the ciphers to use, or create custom ciphers.

== Enable Client Authentication

If the target for the TLS context is Anypoint Security, you can, optionally, enable client authentication.

. Select *Enable Client Authentication*, and provide the following information: +
* *Verification Depth* +
(Optional) Select the maximum depth to allow for the certificate chain verification.
* *Revocation Method* +
(Optional) Select *CRL* to use a certificate revocation list. 
* *Send Trust Store* +
Select this option if you want the edge to send the truststore to the far-end client for mutual TLS.
* *Perform Certificate Pinning* +
Select this option if you want the client to authenticate the server by validating the server's certificate. 
. (Optional) Click *Advanced Options* to expand the available options, and select the options to enable: +
* *Certificate Checking Strength* +
This option allows the application to control whether strict or lax certificate checking is performed during chain-of-trust processing.
* *Certificate Policy Checking* +
Controls certificate policy processing as defined in RFC 3280 and 5280.
A certificate can contain zero or more policies. A policy is represented as an object identifier (OID). In an end entity certificate, this policy information indicates the policy under which the certificate has been issued and the purposes for which the certificate can be used. +
In a CA certificate, this policy information limits the set of policies for certification paths that include this certificate. Applications with specific policy requirements are expected to have a list of those policies that they will accept and to compare the policy OIDs in the certificate to that list. If this extension is critical, the path validation software must be able to interpret this extension (including the optional qualifier), or must reject the certificate.
* *OID* +
Select the object identifier options, which include: +
** *Require Initial Explicit Policy* +
This indicates that the path must be valid for at least one of the certificate policies in the user-initial-policy-set.
** *Certificate Policies* +
At minimum, the Certificate Policies extension consists of a policy identifier (OID). 
* *Authentication Overrides* +
Select the criteria for when to override failing authentication when mutual authentication is being performed. 

== Ciphers

Use the *Ciphers* option to select ciphers to use with the selected TLS version. Each TLS context can have multiple ciphers. 

. Click *Ciphers* to select available ciphers. +
If you select *TLS 1.3*, it is recommended that you keep the default selection, which includes all three of the *TLS* cipher suites. +
If you don't use the defaults and choose to select individual ciphers, select ciphers that match the configured keystore to ensure that TLS can set up a connection. +
* For a keystore with an RSA key (the most common type), select ciphers that contain the string `RSA` (there are some exceptions). 
* If you are using ECC ciphers, select ciphers that contain the string `ECDSA`. +
Consult TLS standards and documentation for more information.
. (Optional) If you selected *Mule* as the TLS context target, you can define custom ciphers to use with your proxy instance.

If you add a cipher that's not supported by the Java runtime, you receive a warning, but this does not prevent you from saving the TLS context.

=== TLS 1.3 Cipher Suites

TLS 1.3 support is available only if you are using the Anypoint Security target. 

The cipher suites for TLS 1.3 are listed with those of TLS 1.2 and TLS 1.1 and appear in the *No known vulnerabilities and support Perfect Forward Secrecy* grouping. There are major changes in the cipher suites that start with the string `TLS`. 

These changes include the following: 

* There are new cipher suites that work only in TLS 1.3. The cipher suites for TLS 1.2 and TLS 1.1 cannot be used for TLS 1.3.  
* The new cipher suites are defined differently from the cipher suites for earlier versions of TLS and do not specify the certificate type (for example, RSA, DSA, ECDSA) or the key exchange mechanism (for example,DHE or ECHDE).

== See Also

* xref:asm-secret-group-creation-task.adoc[Create a Secret Group]