== Add a Keystore
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


Specify the type of keystore to add to the secret group. The keystore is the combination of the authorization certificate, its corresponding private keys, and the certification authority's path.

To add a keystore to your secret group:

. In the *Secret Groups* list view, select the secret group to which to add a keystore, and click *Edit*. 
. Select *Keystore* in the menu on the left, and click *Add Keystore*. 
. In the *Name* field, enter a name for your keystore.
. In the *Type* field, select the keystore type from the drop-down menu.
+
Supported types include:
+
* Privacy-Enhanced Mail (PEM) +
Base64-encoded ASCII file with a `cer`, `crt`, or `pem` extension
* Java Keystore (JKS) +
Repository for authorization or public key certificates
The JKS keystore type does not store secret keys.
* PKCS #12 +
Stores server and intermediate certificates in an archive file format
The PKCS #12 keystore type does not store secret keys.
* Java Cryptography Extension keystore (JCEKS) +
Stores server and intermediate certificates as well as secret keys
.. To add a *PEM* type keystore, you must provide: 
+
** *Certificate File* +
Click *Choose File* to locate and upload the PEM certificate file.  
** *Key File* +
Click *Choose File* to locate and upload the PEM formatted file that contains the private key for the certificate. 
** *Key Passphrase* +
Enter the word or phrase that protects the private key. 
** *CA Path Certificate File* +
Click *Choose File* to locate and upload the certificate signed by a certification authority (CA). +
The CA path contains the intermediary and root certificates that are related to the certificate file you want to use.    
** *Override Expiration Date* +
Select the date to override the default expiration date of the certificate.
.. To add a *JKS*, *PKCS12*, or *JCEKS* type keystore, you must provide: 
+
** *Keystore File* +
Click *Choose File* to locate and upload the keystore file to use.
** *Keystore Passphrase* +
Enter the word or phrase that protects the keystore.
** *Alias* +
The alias used to access the keystore entries (key and trusted certificate entries).
** *Key Passphrase* +
The word or phrase that protects the private key.
** *Algorithm* +
The algorithm to use for encryption of keys.
** *Override Expiration Date* +
Select the date to override the current expiration date of the certificate.
. Click *Save*.