= Add a Certificate Pinset
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


To add a concatenated list of PEM certificates to the secret group:

. In the *Secret Groups* list view, select the secret group to which to add a certificate pinset, and click *Edit*. 
. Select *Certificate Pinset* in the menu on the left, and click *Add Certificate Pinset*. 
. In the *Certificate Pinset* screen, add the required information. +
* *Name* +
Enter a name for the certificate pinset. 
* *Certificate File* +
Click *Choose File* and select the PEM formatted CA certificate to upload.
* *Expiration Date* +
Select the expiration date for the certificate.
. Click *Save*.

== Add a Shared Secret

Add a shared secret users can use for authentication. 

. In the *Secret Groups* list view, select the secret group to which to add a shared secret, and click *Edit*. 
. Select *Shared Secret* in the menu on the left, and click *Add Shared Secret*. 
. In the *Add Shared Secret* screen, add the required information. 
+
* *Name* +
Enter a name for your shared secret.
* *Type* +
Select the shared secret type from the drop-down menu.
 ** *Username Password* +
 Provide a username and password.
 ** *Symmetric Key* +
 Provide a Base64 string containing symmetric key.
 ** *S3 Credential* +
 Provide the access key ID and the secret access key to an S3 bucket.
 ** *Blob* +
 Provide a Base64-encoded value.
. Click *Save*.