= TLS Context
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you create a secret group, you can add a TLS context to encrypt inbound traffic to Anypoint Runtime Fabric (Runtime Fabric) or Mule 4 proxies. 

//Do we need to spell out TLS at first use above?//

You can use the TLS context you store in the secrets manager either when you configure an HTTPS API proxy, or to validate the SSL handshake in the edge endpoint of Runtime Fabric.

//This container topic intro text should also prepare your audience for the other subtopics besides adding: enabling client auth, selecting ciphers, and cipher suite reference.//

//GLOBALLY ensure that your container intros summarize subcontent at the next title level: = should summarize contained ==; == should summarize contained ===; === hopefully does not contain ====, which is nesting info too deeply.//


== Add TLS Context 

Adding a TLS context to your secret group involves supplying a name; target; security information; version; keystore and, optionally, truststore; and expiration date. 

//Previous suggestion just an attempt to add some value to the task intro.//

. In the *Secret Groups* list view, select the secret group to which to add a TLS context. 
. Select *TLS Context* in the menu on the left, and click *Add TLS Context*. 
. In the Create TLS Context screen, add the required information:
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select the target for the TLS context from the drop-down list:
** *Anypoint Security* +
Validates the SSL handshake for Runtime Fabric. +
If you choose *Anypoint Security*, you can select keystores and truststores that are either PEM or non-PEM types. Supported types include: +
*** JKS
*** PKCS12
*** JCEKS 
** *Mule* +
Uses the TLS context as the SSL validation for Mule 4-based API proxies.
* *TLS Version* +
Select from the following supported TLS versions: 
+
[%header%autowidth.spread,cols="a,a"]
|===
|Target |Supported TLS Version
|Mule a| * TLS 1.1
* TLS 1.2

|Anypoint Security a| * TLS 1.1
* TLS 1.2
* TLS 1.3
|===    
* *Keystore* +
From the drop-down list, select the keystore to store the TLS context.
* *Truststore* +
Optionally select from the list a truststore to add the TLS context. +

//Do we need to say anything here about why this is optional or under what circumstances the user would want or need to take this step? Something like "If you want <this>, then select...a truststore...."//

If the Target value for the TLS context is Mule, you can select *Insecure* if you don't want certificate validation enforced. 
* *Expiration Date* +
Optionally select the expiration date for the certificate.

//ditto re. when would a user do this?//

. Click *Save*.

Additionally, you can enable client authentication and select the ciphers to use, or create custom ciphers.

//The sentence above confuses me. I earlier suggested that these be mentioned in the intro to the whole set of subtopics, in the container topic text. But...are these actually subtasks of the ADD task?//

== Enable Client Authentication

If you choose a Target value of the target Anypoint Security when adding your TLS contex, you can optionally enable client authentication.

//Under what circumstances does the user want or need to perform this optional task?//

. Select *Enable Client Authentication* and provide the following information: +
* *Verification Depth* +
Optionally select the maximum depth to allow for the certificate chain verification.
* *Revocation Method* +
Optionally select *CRL* to use a certificate revocation list. 
* *Send Trust Store* +
Select this option if you want the edge to send the truststore to the far-end client for mutual TLS.

//Note the wording of the previous description: it is conditional ("if you want"), indicating that this item is also optional. I suggest rewording all of these descriptions to "If you want <this>, select <that>." The "If" implies that the step is optional.//

* *Perform Certificate Pinning* +
Select this option if you want the client to authenticate the server by validating the server's certificate. 
. (Optional) Click *Advanced Options* to expand the available options, and select the options to enable: +

//DITTO previous edits about representing optional steps and reasons for them.//

* *Certificate Checking Strength* +
Allows the application to control whether strict or lax certificate checking is performed during chain-of-trust processing.
* *Certificate Policy Checking* +
Controls certificate policy processing as defined in RFC 3280 and 5280.

//Do we really have to provide all of this conceptual information in our task steps? I would be tempted to let "as defined in RFC..." be the end of it....//

A certificate can contain zero or more policies. A policy is represented as an object identifier (OID). In an end entity certificate, this policy information indicates the policy under which the certificate has been issued and the purposes for which the certificate can be used. +
In a CA certificate, this policy information limits the set of policies for certification paths that include this certificate. Applications with specific policy requirements are expected to have a list of those policies that they will accept and to compare the policy OIDs in the certificate to that list. If this extension is critical, the path validation software must be able to interpret this extension (including the optional qualifier), or must reject the certificate.
* *OID* +
Select the object identifier options, which include: +
** *Require Initial Explicit Policy* +
Indicates that the path must be valid for at least one of the certificate policies in the user-initial-policy-set.

//why all the hyphens above?//

** *Certificate Policies* +
At minimum, consists of a policy identifier (OID). 
* *Authentication Overrides* +
Select the criteria for when to override failing authentication when mutual authentication is being performed. 
. Click *Save*.

== Select Ciphers

Use the *Ciphers* option to select ciphers to use with the selected TLS version. Each TLS context can have multiple ciphers.

//DITTO comments at the beginning of the previous subtopic//

. Click *Ciphers* to select available ciphers. +

//There is way too much text between the step above and the next step. Task steps should include one user action apiece. Consider omitting all of this info, or moving it to the task intro or another topic. Another approach is to make each choice a separate step: "If you select a TLS Version value of *TLS 1.3* keep the default..." and then a second step of "If you <select another version? do not use the defaults?>, select ciphers that match...: <list>". This is still an awful lot of text for two steps....//

If you select a TLS Version value of *TLS 1.3*, keep the default selection, which includes all three of the TLS cipher suites. +

//We have not yet described the cipher suites. Maybe that info should come before this task rather than after it?//

If you don't use the defaults, select ciphers that match the configured keystore to ensure that TLS can set up a connection: +
* For a keystore with an RSA key (the most common type), select ciphers that contain the string `RSA` (there are some exceptions). 

//Reconsider the parenthetical text in the step above. It really confuses the meaning, and since we don't describe the exceptions, the meaning of the second paren is incomplete.//

* If you are using ECC ciphers, select ciphers that contain the string `ECDSA`. +
Consult TLS standards and documentation for more information. 
* If a client device supports AES-dedicated CPU instructions, use the AES-GCM ciphers. 
* If the client does not support AES-dedicated instructions (some mobile and IoT devices), the client negotiates to use `CHACHA20-POLY1305`. It takes two (client and server) to do the CHACHA.

//This fourth list item is not parallel with the three previous, becaue it is not telling the user what to select. Should it really be subordinate plain text to the third bullet?//

. If you selected *Mule* as the Target value for the TLS context, you can define custom ciphers to use with your proxy instance.
. Click *Save*.

If you add a cipher that's not supported by the Java runtime, you receive a warning, but this does not prevent you from saving the TLS context.

//Do we need to say more about ciphers supported by Java?//

=== TLS 1.3 Cipher Suites

TLS 1.3 support is available only if you are using the Anypoint Security target. 

The cipher suites for TLS 1.3 are listed with those of TLS 1.2 and TLS 1.1 and appear in the *No known vulnerabilities and support Perfect Forward Secrecy* grouping. There are major changes in the cipher suites that start with the string `TLS`: 

//Major changes from what? All of the ciphers described above are TLS....//

* The new cipher suites for TLS 1.3 cannot be used with TLS 1.1 and TLS 1.2. 
* The cipher suites for TLS 1.2 and TLS 1.1 cannot be used for TLS 1.3.  
* The new cipher suites for TLS 1.3 are defined differently from the cipher suites for earlier versions of TLS and do not specify the certificate type (for example, RSA, DSA, ECDSA) or the key exchange mechanism (for example, DHE or ECHDE).

== See Also

* xref:asm-secret-group-creation-task.adoc[Create a Secret Group]
