= Add a Certificate
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

//Can we add some chronological context here, as well as something about what PEM or end-entity certificates are and WHY the audience has to add them:
"After you create a secret group, you must add a PEM certificate to it. A PEM certificate <is this, does this>. You add only one <because>. This certificate is the "leaf" (end-entity) certificate to the <branch? tree? whatever makes this a "leaf"...>."//

Add a single PEM certificate to the secret group. This certificate is the "leaf" certificate (end-entity certificate). 

. In the Secret Groups list view, select the secret group you need to add a certificate to and click *Edit*. 
. In the menu on the left, select *Certificate* and then click *Add Certificate*. 
. In the *Add Certificate* screen, complete these fields: 
+
* *Name* +
Enter a name for your certificate.
* *Type* +
Select *PEM* from the drop-down menu.
* *Certificate File* +
Click *Choose File*, and select the certificate file to upload.
* *Override Expiration Date* +
Optionally select a date to override the default expiration date of the certificate.

//Why or under what circumstances would a user want to do this? 
How does the user know the default expiration date?//

. Click *Save*.

//Is there anything useful to add here about the state of the environment after the user completes this task or what the user does next?//

== See Also

* xref:asm-secret-group-creation-task.adoc[Create a Secret Group]
* xref:secret-group-add-tls-context.adoc[Add a TLS Context]
