= TLS Context
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you create a secret group, you can add a TLS context to encrypt inbound traffic to Runtime Fabric or Mule 4 proxies. 

You can use the TLS context you store in Secrets Manager either when you configure an HTTPS API Proxy, or to validate the SSL handshake in the edge endpoint of Runtime Fabric.

== Add TLS Context 

Add a TLS context to your Secret Group. 

. In the *Secret Groups* list view, select the secret group to which to add a TLS context. 
. Select *TLS Context* in the menu on the left, and click *Add TLS Context*. 
. In the Create TLS Context screen, add the required information.
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select the target for the TLS context from the drop-down list. 
** *Anypoint Security* +
Validates the SSL handshake for Runtime Fabric. +
If you use the *Anypoint Security* target, you can select keystores and truststores that are either PEM or non-PEM types. Supported types include: +
*** JKS
*** PKCS12
*** JCEKS 
** *Mule* +
Uses the TLS context as the SSL validation for Mule 4 based API proxies.
* *TLS Version* +
Select the TLS version. Supported versions include: 
+
[%header%autowidth.spread,cols="a,a"]
|===
|Target |Supported TLS Version
|Mule a| * TLS 1.1
* TLS 1.2

|Anypoint Security a| * TLS 1.1
* TLS 1.2
* TLS 1.3
|===    
* *Keystore* +
Select the keystore to store the TLS context in from the drop-down list.
* *Truststore* +
(Optional) Select a truststore to add the TLS context to from the drop-down list.
* *Expiration Date* +
(Optional) Select the expiration date for the certificate.
. Click *Save*.

Additionally, you can enable client authentication and select the ciphers to use, or create custom ciphers.

== Enable Client Authentication

. Select *Enable Client Authentication*, and provide the following information: +
* Verification Depth +
(Optional)
* Revocation Method +
(Optional)
* Send Trust Store
* Perform Certificate Pinning
. (Optional) Click Advanced Options to expand the available options, and select the options to enable: +
* Certificate Checking Strength +
* Certificate Policy Checking +
* OID +
* Authentication Overrides +

== Ciphers

The *Ciphers* option allows you to select ciphers for the selected TLS version. Each TLS context can have multiple ciphers. 

. Click *Ciphers* to select available ciphers. +
If you selected TLS 1.3, it is recommended that you keep the default selection, which includes all three of the *TLS* cipher suites. 
. (Optional) If you selected *Mule* as the TLS context target, you can define custom ciphers to use with your proxy instance.

If you add a cipher that's not supported by the Java runtime, you receive a warning, but this does not prevent you from saving the TLS context.


== See Also

* xref:asm-secret-group-creation-task.adoc[Create a Secret Group]