= Sensitive Information Detection

Sensitive Information Detection (SID) allows you to identify where you have potential leakage of sensitive information.

These are some common scenarios where implementing SID can help you keep sensitive data more secure: 

* Developers use sensitive information when they build apps. If developers aren’t aware of what is sensitive information and what is not, they can inadvertently cause leakage by exposing the sensitive information.
* Developers build test APIs, or add testing parameters to existing APIs, that return sensitive information. These APIs or parameters were not documented, and the developer forgets to remove the sensitive information from the API.  
* Data is received from partners that may contain sensitive information, which should be cleansed.


== WAF Security Policy Summary Log

When you apply the WAF policy to the Runtime Fabric, a `rtfWafSecurityPolicySummary` log is generated, which shows the WAF category, rule ID, and count for how many times the violation was detected. 
For example:

[json]
----
{
	"timeStamp": "2019-04-15T16:13:00.045Z",
	"collectionIntervalInMinutes": "1",
	"node": "node-host",
	"wafSummary": {
		"requestScannerDetection": [

		],
		"requestProtocolEnforcement": [

		],
		"requestProtocolAttack": [

		],
		"requestApplicationAttackLfi": [

		],
		"requestApplicationAttackRfi": [

		],
		"requestApplicationAttackRce": [

		],
		"requestApplicationAttackPhp": [

		],
		"requestApplicationAttackXss": [

		],
		"requestApplicationAttackSqli": [

		],
		"requestApplicationAttackSessionFixation": [

		],
		"requestSidPiiCore": [{
			"ruleId": "600100",
			"count": 1
		}],
		"requestSidPiiEnhanced": [

		],
		"requestSidPci": [

		],
		"requestSidPhi": [

		],
		"responseDataLeakages": [

		],
		"responseDataLeakagesSql": [

		],
		"responseDataLeakagesJava": [

		],
		"responseDataLeakagesPhp": [

		],
		"responseDataLeakagesIis": [

		],
		"responseSidPiiCore": [

		],
		"responseSidPiiEnhanced": [

		],
		"responseSidPci": [

		],
		"responseSidPhi": [

		]
	}
}
----

== SID Summary Log

When you apply the WAF policy to the Runtime Fabric, a `rtfSidSummary` log is generated, which shows the WAF category, rule ID, and count for how many times the violation was detected. 
For example:

[json]
----
{
	"timeStamp": "2019-04-15T16:13:00.045Z",
	"collectionIntervalInMinutes": "1",
	"node": "node-host-name",
	"sidSummary": {
		"api": "/Post",
		"rule": "TAXID",
		"direction": "Request",
		"count": 1
	}
}
----

== Rule Categories and IDs

This table lists the rule categories and rule IDs for SID that are returned in the logs.

[%header%autowidth.spread,cols="a,a,a"]
|===
|Rule |Rule Category | RuleId
|TAXID	
|PII-Core	
|600100

|SSN	
|PII-Core	
|600110

|SSN VALUE	
|PII-Core	
|600120

|Social Security Number key value pair	
|PII-Core	
|600130

|DOB	
|PII-Core	
|600140

|FIRST NAME	
|PII-Core	
|600150

|LAST NAME	
|PII-Core	
|600160

|CONTACT_NUMBER	
|PII-Enhanced	
|600200

|EADDRESS	
|PII-Enhanced	
|600210

|USER NAME	
|PII-Enhanced	
|600220

|PASSPORT	
|PII-Enhanced	
|600230

|DRIVER LICENSE	
|PII-Enhanced	
|600240

|DOMESTIC PHONE NUMBER	
|PII-Enhanced	
|600250

|INTERNATIONAL PHONE NUMBER	
|PII-Enhanced	
|600260

|ACCOUNT NUMBER	
|PCI	
|600300

|BANK CARD	
|PCI	
|600310

|VISA CARD	
|PCI	
|600320

|MASTER CARD	
|PCI	
|600330

|AMX CARD	
|PCI	
|600340

|DISCOVER CARD	
|PCI	
|600350

|DINERSCLUD CARD	
|PCI	
|600360

|JCB CARD	
|PCI	
|600370

|Credit Card number key value pair	
|PCI	|600380

|MEDICAL CARD	
|PHI	
|600400
|===