= Sensitive Information Detection

Sensitive Information Detection (SID) allows you to identify where you have potential leakage of sensitive information.

== WAF Security Policy Summary Log

When you apply the WAF policy to the Runtime Fabric, a `rtfWafSecurityPolicySummary` log is generated, which shows the WAF category, rule ID, and count for how many times the violation was detected during the last collection interval. 
For example:

[json]
----
{
	"timeStamp": "2019-04-15T16:13:00.045Z",
	"collectionIntervalInMinutes": "1",
	"node": "node-host",
	"wafSummary": {
		"requestScannerDetection": [

		],
		"requestProtocolEnforcement": [

		],
		"requestProtocolAttack": [

		],
		"requestApplicationAttackLfi": [

		],
		"requestApplicationAttackRfi": [

		],
		"requestApplicationAttackRce": [

		],
		"requestApplicationAttackPhp": [

		],
		"requestApplicationAttackXss": [

		],
		"requestApplicationAttackSqli": [

		],
		"requestApplicationAttackSessionFixation": [

		],
		"requestSidPiiCore": [{
			"ruleId": "600100",
			"count": 1
		}],
		"requestSidPiiEnhanced": [

		],
		"requestSidPci": [

		],
		"requestSidPhi": [

		],
		"responseDataLeakages": [

		],
		"responseDataLeakagesSql": [

		],
		"responseDataLeakagesJava": [

		],
		"responseDataLeakagesPhp": [

		],
		"responseDataLeakagesIis": [

		],
		"responseSidPiiCore": [

		],
		"responseSidPiiEnhanced": [

		],
		"responseSidPci": [

		],
		"responseSidPhi": [

		]
	}
}
----

== SID Summary Log

When you apply the WAF policy to the Runtime Fabric, a `rtfSidSummary` log is generated, which shows the offending API, rule description, direction, and count for the number of times the SID rule was triggered. 
For example:

[json]
----
{
	"timeStamp": "2019-04-15T16:13:00.045Z",
	"collectionIntervalInMinutes": "1",
	"node": "node-host-name",
	"sidSummary": {
		"api": "/Post",
		"rule": "TAXID",
		"direction": "Request",
		"count": 1
	}
}
----

== View Rule Categories and IDs in RAML

You can view the the SID categories and rule IDs in the Anypoint Security RAML (`security-fabric-policies-api-<version>.raml`). 

. Go to Anypoint Exchange.
. Search for "Anypoint Security Policies API" and download the RAML.
. Extract the ZIP files.
. Navigate to `<Download_location>/anypoint-security-policies-api-<version>-raml 3/dataTypes/policies/WafRules/`
