= Tokenization Service Scenarios


The way you configure and use the Tokenization service varies according to your implementation.


== Prerequisites

To configure the tokenization service, you need to:

. xref:1.2@runtime-fabric::install-create-rtf-arm.adoc[Install Runtime Fabric].
. xref:1.2@runtime-fabric::enable-inbound-traffic.adoc[Enable inbound traffic] on Runtime Fabric. 
* A secret group to store the tokenization table encryption keys. The tokenization service creates and stores its own keys. See xref:asm-secret-group-concept.adoc[Secrets Manager documentation].
* You must have the following permissions: 
** API Manager *Manage Policies*
** Tokenization *Manage Tokenization Services* + 
See xref:2.x@api-manager::environment-permission-task.adoc[Granting Permission to Access an Environment]

== Configure Tokenization Using an API Gateway Policy

You can add the Tokenization service policy as one of the provided policies for the API Gateway. For more information, see xref:apply-tokenization-policy-to-api.adoc[Use Tokenization and Detokenization as API Gateway Policies].

This is the high level workflow for this scenario:

. Ensure you have completed the required prerequisites. 
. xref:tokenization-formats.adoc[Create a tokenization format].
. xref:create-tokenization-service.adoc[Create a tokenization service].
. In API Manager, xref:2.x@api-manager::getting-started-proxy.adoc[set up the API gateway] for the Mule app to serve as the proxy. 

== Configure Tokenization Using a Mule App

When extra data processing is required, you can expose the Tokenization endpoint through a Mule app. For more information, see xref:tokenization-example.adoc[Expose Tokenization as a Service Directly to Mule Applications].

This is the high level workflow for this scenario:

. Ensure you have completed the required prerequisites. 
. Create an API from the tokenization RAML.
. Configure TLS.
