= Tokenization Service Scenarios


The way you configure and use the Tokenization service depends on your Mule implementation.

== Configure Tokenization Using an API Gateway Policy

You can use the tokenization service as the core engine for the tokenization and detokenization provided policies in API Manager. For more information, see xref:apply-tokenization-policy-to-api.adoc[Use Tokenization and Detokenization as API Gateway Policies].

This is the high level workflow for this scenario:

. Ensure you have completed the required prerequisites. 
. xref:tokenization-formats.adoc[Create a tokenization format].
. xref:create-tokenization-service.adoc[Create a tokenization service].
. In API Manager, xref:2.x@api-manager::getting-started-proxy.adoc[set up the API gateway] for the Mule app to serve as the proxy. 
. Apply xref:2.x@api-manager::policy-mule4-tokenization.adoc[the tokenization policy] to the API gateway.

== Configure Tokenization Using a Mule App

When extra data processing is required, you can expose the Tokenization endpoint through a Mule app. For more information, see xref:tokenization-example.adoc[Expose Tokenization as a Service Directly to Mule Applications].

This is the high level workflow for this scenario:

. Ensure you have completed the required prerequisites. 
. Create an API from the tokenization RAML.
. Configure TLS.
