= WAF Rulesets

You can enable rules by threat category for requests and responses--these are called "rulesets." Custom rules or modifications to rules are not currently available. There is an option to disable individual rules within a ruleset if they are causing false positives. See xref:create-waf-policy#disable_rules[Disable Individual Rules].

Rules can run on a variety of things, for example, they can run on URIs, headers, arguments, session IDs, cookies, and request and response bodies, to name a few.

For optimal performance, you should enable only the rules that apply to your web application's technology.

[[request_rule_sets]]
== Request Rulesets

Request rulesets are divided into ten threat categories, which are called rulesets. There are three actions that can be selected for each ruleset:

* *Disable ruleset* - (Default) Ruleset detection is turned off.
* *Detect and allow violations* - The violation is detected and you will get information in your logs at the INFO level, per incident. +
They will also be included at the ERROR (default log level for Edge policies) level in a summary report. +
You can change log levels for your security policies in Runtime Fabric *Logs* settings. See xref:1.0@runtime-fabric::index.adoc[the Runtime Fabric documentation].
* *Detect and reject violations* - The request is rejected and has a response status of `400 - BAD REQUEST`.

The ten threat categories include the following:

* *Scanner detection*
* *Protocol enforcement*
* *Protocol attack*
* *Local file inclusion*
* *Remote file inclusion*
* *Remote code execution*
* *PHP injection*
* *Cross-site scripting*
* *SQL injection*
* *Session fixation*

[[response_rule_sets]]
== Response Rule Sets

Response rulesets are similar to request rulesets. Response rulesets check outbound responses from backend servers to look for information that should not be present in responses.

The response rulesets are again divided into threat categories. The same actions apply as with the request ruleset--disable ruleset, disable and reject violations, and disable and allow violations. These have the same meaning as they do in the request ruleset.

The threat categories for the response ruleset include:

* *Data leakages*
* *SQL data leakages*
* *Java data leakages*
* *PHP data leakages*
* IIS data leakages*

== View Rules in RAML

You can understand the regular expressions that make up each rule by viewing the rules in the RAML. Not all OWASP CRS rules for each category are enabled for the WAF policy. A very small number of them are not included for various reasons. View the RAML for the exact contents and rule IDs that are included.
