= WAF Rulesets

You can enable rules by threat category for requests and responses--these are called "rulesets." Custom rules or modifications to rules are not currently available. There is an option to disable individual rules within a ruleset if they are causing false positives.

You should enable only the rules that apply to your web application's technology.

[[request_rule_sets]]
== Request Rule Sets

Request rulesets are divided into ten threat categories, which are called rulesets. There are three actions that can be selected for each ruleset:

* Disable ruleset - (Default) Ruleset detection is turned off.
* Detect and reject violations - When a request is detected that matches one of the rules contained in the ruleset, the request will be rejected with a Response status code of `400 - BAD REQUEST`. If there is an optional DoS policy configured, this error will be reported to DoS which will threshold the error against the source IP address.
* Detect and allow-violations - The request is allowed to proceed and the detection is not reported to DoS. A statistics counter per rule ID detected will be incremented, which will then be shown in the WAF summary log.

The ten threat categories include the following:

* *Scanner detection*
* *Protocol enforcement*
* *Protocol attack*
* *Local file inclusion*
* *Remote file inclusion*
* *Remote code execution*
* *PHP injection*
* *Cross-site scripting*
* *SQL injection*
* *Session fixation*

[[response_rule_sets]]
== Response Rule Sets

Response rulesets are similar to request rulesets. Response rulesets check outbound responses from backend servers to look for information that should not be present in responses.

The response rulesets are again divided into threat categories. The same actions apply as with the request ruleset--disable ruleset, disable and reject violations, and disable and allow violations. These have the same meaning as they do in the request ruleset.

The threat categories for the response ruleset include:

* *Data leakages*
* *SQL data leakages*
* *Java data leakages*
* *PHP data leakages*
* IIS data leakages*

== View Rules in RAML

You can understand the regular expressions that make up each rule by viewing the rules in the RAML. Not all OWASP CRS rules for each category are enabled for the WAF policy. A very small number of them are not included for various reasons. View the RAML for the exact contents and rule IDs that are included.
