//tag::connectedSelect[]
[[select-ciphers]]
== Select Ciphers

When you configure a TLS context, Secrets Manager applies default ciphers based on the TLS versions you select. In addition to the defaults, you can select other ciphers to use with the selected TLS version. Each TLS context can have multiple ciphers.

To select ciphers:

. Click *Ciphers* to see available ciphers. 
. Select ciphers.
+
Cipher selection is not available if only supporting TLS version 1.3.
. Click *Save*

//end::connectedSelect[]

//tag::cipherSupport[]

== TLS Cipher Support on Flex Gateway

Flex can support a range of TLS Versions from TLS 1.1 to TLS 1.3, and you can also customize some of the ciphers to support.

You cannot customize the list of TLS 1.3 Ciphers. If you support TLS 1.3, you must support the TLS 1.3 default ciphers.

If you support TLS 1.2, the TLS 1.2 default Ciphers are selected. However, unlike TLS 1.3, you can customize different TLS 1.2 ciphers.

There are no default ciphers for TLS 1.1. If you choose to support TLS 1.1, you must select the ciphers you want to support.

IMPORTANT: Ensure that your API upstream supports the selected ciphers and versions.

//end::cipherSupport[]

//tag::cipherSupportLocal[]
[[local-support]]
== TLS Cipher Support on Flex Gateway

Flex can support a range of TLS Versions from TLS 1.1 to TLS 1.3, and you can also customize some of the ciphers to support.

You cannot customize the list of TLS 1.3 Ciphers. If you support TLS 1.3, the TLS 1.3 default ciphers are all supported regardless of the ciphers listend in the configuration file. If you don't support TLS 1.3, these ciphers are not included.

For TLS 1.2, listing any ciphers overides the TLS 1.2 default ciphers. If you want to list ciphers besides the default TLS 1.2 Ciphers, you must list every cipher to support including the default ciphers you want to support. Excluding default ciphers from your list of supported ciphers means you do not support those ciphers. If you wish to only support the default ciphers, you can leave the cipher list blank. Listing ciphers does not affect the default TLS 1.3 cipher.  

There are no default ciphers for TLS 1.1. To support TLS 1.1, you must list the ciphers to support. If you support TLS 1.1 and TLS 1.2, listing TLS 1.1 ciphers overides the TLS 1.2 defaults. To support both these versions, list all ciphers you want to support.

IMPORTANT: Ensure that your API upstream supports the selected ciphers and versions.
//end::cipherSupportLocal[]

//tag::ciphers[]

=== Flex Gateway Supported Ciphers

Flex Gateway supports the following TLS Ciphers in connected and local mode:

[%header%autowidth.spread,cols="a,a,a,a"]
|===
| Cipher | TLS Version | Default | Advice
| TLS_AES_128_GCM_SHA256 | 1.3 | Yes | Secure
| TLS_AES_256_GCM_SHA384 | 1.3 | Yes | Secure
| TLS_CHACHA20_POLY1305_SHA256 |1.3 | Yes | Secure
| TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 | 1.2 | Yes | Secure
| TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 | 1.2 | Yes | Secure
| TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 | 1.2 | Yes | Secure
| TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 | 1.2 | Yes | Secure
| TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 | 1.2 | Yes | Secure
| TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 | 1.2 | Yes | Secure
| TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 | 1.2 | No | Secure
| TLS_RSA_WITH_AES_128_GCM_SHA256 | 1.2 | No | Weak
| TLS_RSA_WITH_AES_256_GCM_SHA384 | 1.2 | No | Weak
| TLS_RSA_WITH_NULL_SHA | 1.1, 1.2 | No | Insecure
| TLS_RSA_WITH_AES_128_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_RSA_WITH_AES_256_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_PSK_WITH_AES_128_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_PSK_WITH_AES_256_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA | 1.1, 1.2 | No | Weak
| TLS_RSA_WITH_3DES_EDE_CBC_SHA | 1.1 | No | Weak
|===


//end::ciphers[]
