//tag::intro1[]
After you xref:asm-secret-group-creation-task.adoc[create a secret group] and xref:asm-secret-group-creation-task.adoc#adding-a-keystore[add a keystore], you can add a Transport Layer Security (TLS) context and apply the TLS context to API Instances to encrypt their inbound and outbound traffic. 

//end::intro1[]
//tag::intro2[]
Flex Gateway supports inbound and outbound TLS and mutual authentication TLS (mTLS) for the outbound connection.

When you add the TLS context, you can also select the ciphers to use with the TLS context and you can configure different inbound and outbound validation settings.
//end::intro2[]


//tag::intro3[]
You can use the TLS context you store in secrets manager when you configure an HTTPS API in Flex Gateway Connected Mode.

//end::intro3[]

//tag::byb[]

== Before You Begin

Before adding the TLS context to Flex Gateway, you must complete the following tasks:

* xref:anypoint-security::asm-secret-group-creation-task.adoc[Create a Secret Group]
* xref:anypoint-security::asm-secret-group-creation-task.adoc#adding-a-keystore[Add a Keystore]

//end::byb[]

//tag::addContextTitle[]
== Add a TLS Context

//end::addContextTitle[]

//tag::addContext[]
Adding a TLS context to your secret group requires supplying a name, target, version, and keystore. Optionally, you can add a truststore, context experation date, ALPN Protocols, and configure the inbound and outbound settings. 

WARNING: If you edit a secret group, including a TLS context, that is currently applied to an API Instance, you must redploy the API Instance to apply the changes. You must individual redeploy all instances affected by the change.
+
To redeploy an API Instance:

. Go to *Anypoint Platform > API Manager*.
. Click the name of the API Instance to redploy.
. Click *Runtime & Endpoint Configuration > Save & Apply*.

To add a TLS Context:

. Go to *Anypoint Platform > Secrets Manager*.
. In the *Secret Groups* list view, click the *Edit* button of the secret group to add a TLS context. 
. Select *TLS Context* in the menu on the left, and click *Add TLS Context*. 
. In the Create TLS Context screen, add the required information:
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select *Flex Gateway* to use the TLS context as the SSL validation for Flex Gateway APIs. 
* *Min TLS Version* and *Max TLS Version*+
By default, TLS 1.3 and TLS 1.3 are selected as the minimum and maximum supported versions. You can select to support a different minimum and maximum or select to support a single version by selecting the same version for both the minimum and maximum.  
* *Keystore* +
From the drop-down list, select the keystore to store the TLS context.
* *Truststore* +
Optionally, select a truststore to which to add the TLS context if you are using a truststore to store certificates trusted by the client. +
* *Expiration Date* +
Optionally, select the expiration date for the certificate.
* *ALPN Protocols* +
By default, *H2 - HTTP/1.1* is the selected ALPN protocols. Change this value to support different protocols. 
* *Inbound Settings* +
Optionally, select *Validate Client certificate* to support mTLS for inbound traffic.
* *Outbound Settings* +
Optionally, select *Skip server certificate validation* to skip the validation of the outbound server.

. Optionally, xref:anypoint-security::cipher-suites.adoc[select ciphers] for the TLS context.
. Click *Save*.
//end::addContext[]
