//tag::intro1[]
After you xref:asm-secret-group-creation-task.adoc[create a secret group], you can add a Transport Layer Security (TLS) context and apply the TLS context to API Instances to encrypt their inbound and outbound traffic. When you add the TLS context, you can select the ciphers to use with the TLS context and you can configure different inbound and outbound validation settings.

//end::intro1[]
//tag::intro2[]
Flex Gateway supports inbound and outbound TLS and mutual authentication TLS (mTLS) for the outbound connection.

//end::intro2[]
//tag::intro3[]
TLS context configuration for a Flex Gateway Connected Mode is the same whether it is running in a Docker container, as a Linux Service, or as a Kubernetes Ingress controller.

//end::intro3[]

//tag::intro4[]
You can use the TLS context you store in the secrets manager when you configure an HTTPS API in Flex Gateway Connected Mode.

//end::intro4[]

//tag::byb[]

== Before You Begin

Before adding the TLS context to Flex Gateway, you must complete the following tasks:

* xref:asm-secret-group-creation-task.adoc[Create a Secret Group] 

//end::byb[]

//tag::addContextTitle[]
== Add TLS Context

//end::addContextTitle[]

//tag::addContext[]
Adding a TLS context to your secret group requires supplying a name, target, security information, version, and keystore. Optionally, you can add a truststore, context experation date, ALPN Protocols, inbound settings, and outbound settings. 




To add a TLS Context:

. In the *Secret Groups* list view, select the secret group to which to add a TLS context. 
. Select *TLS Context* in the menu on the left, and click *Add TLS Context*. 
. In the Create TLS Context screen, add the required information:
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select *Flex Gateway* to use the TLS context as the SSL validation for Flex Gateway APIs. 
* *TLS Version* +
By default, TLS 1.1 and TLS 1.3 are selected as the minimum and maximum versions supported versions of TLS. You can select to support a different minimum and maximum or a single version.  
* *Keystore* +
From the drop-down list, select the keystore to store the TLS context.
* *Truststore* +
Optionally select a truststore to which to add the TLS context if you are using a truststore to store certificates trusted by the client. +
* *Expiration Date* +
Optionally select the expiration date for the certificate.


If the Target value for the TLS context is *Flex Gateway*, you can select *Insecure* if you don't want certificate validation enforced. 
. Optionally xref:cipher-suites.adoc[select ciphers] for the TLS context.
. Click *Save*.
//end::addContext[]
