//tag::intro1[]
Using encryption, Transport Layer Security (TLS) policies protect communication between clients, API Instances, and upstream services. After you xref:asm-secret-group-creation-task.adoc[create a secret group], you can add a TLS context or a mutual authentication TLS (mTLS) context and apply the TLS context to API Instances in API Manager to encrypt their inbound and outbound traffic.

//end::intro1[]
//tag::intro2[]
When you add a TLS context, you can also select the ciphers to use with the TLS context and configure different inbound and outbound validation settings.

You can use the TLS context you store in secrets manager when you configure an HTTPS API in Flex Gateway Connected Mode.

//end::intro2[]


//tag::byb[]

== Before You Begin

Before adding a TLS context to Flex Gateway, complete the following tasks:

* xref:anypoint-security::asm-secret-group-creation-task.adoc[Create a Secret Group]
+
When adding a secret group, refer to the <<tls-configuration-options, TLS Configuration Options>>. Depending on your desired configuration, you must add either a PEM Type Keystore or a PEM Type Truststore to your secret group. Complete the following task for your configuration:

** xref:asm-secret-group-creation-task.adoc#adding-a-keystore[Add a Keystore]
** xref:asm-secret-group-creation-task.adoc#adding-a-truststore[Add a Trustore]

//end::byb[]

//tag::configurationOptions[]

[[tls-configuration-options]]
== TLS Configuration Options
You can configure you TLS Context to support regular TLS and mTLS in both the inbound and outbound direction. Depending on the desired configuration, you must add different files to your secret group and select different configuration options.

Refer to the following cross reference table for the required TLS context configuration settings you need in the <<add-a-tls-context, Add a TLS Context>> step:

[%header%autowidth.spread,cols="a,a,a,a,a"]
|===
| Parameter | Inbound TLS | Inbound mTLS | Outbound TLS | Outbound mTLS
| *Keystore* | Required | Required | Not Used | Required
| *Truststore* | Not Used | Required | Required, unless skip server cert validation is Selected | Required to validate upstream certificate
| *Validate Client certificate* | Not Selected | Selected | Not Used | Not Used
| *Skip server certificate validation* | Not Used | Not Used | Not Selected | Selected 
|===

A parameter that is "Not Used" for a configuration implies its status does not affect configuration.

To simplify your configurations, you can create different TLS Contexts for the different traffic directions of you API Instance. However, you can also use the same TLS Context to support different traffic directions, but you cannot support TLS and mTLS for the same direction using the same context. If you use the same TLS context for different directions, ensure you include the required parameters for both directions.

//end::configurationOptions[]

//tag::addContext[]

[[add-a-tls-context]]
== Add a TLS Context for Flex Gateway

Adding a TLS context to your secret group requires supplying a name, target, version, and a keystore or truststore. Optionally, you can add context expiration date, ALPN Protocols, and configure the inbound and outbound settings. 

[WARNING]
====
If you edit a secret group, including a TLS context, that is currently applied to an API Instance, you must redeploy the API Instance to apply the changes. You must individually redeploy all instances affected by the change. To redeploy API Instances, see <<redeploy-api-instance, Redeploy an API Instance>>.
====

To add a TLS Context:

. Go to *Anypoint Platform > Secrets Manager*.
. In the *Secret Groups* list view, click the *Edit* button of the secret group to add a TLS context. 
. Select *TLS Context* in the menu on the left, and click *Add TLS Context*. 
. In the Create TLS Context screen, add the required information:
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select *Flex Gateway* to use the TLS context as the SSL validation for Flex Gateway APIs. 
* *Min TLS Version* and *Max TLS Version* +
By default, TLS 1.3 and TLS 1.3 are selected as the minimum and maximum supported versions. You can select to support a different minimum and maximum or select to support a single version by selecting the same version for both the minimum and maximum.  
* *Keystore* +
From the drop-down list, select the keystore to store the TLS context. Only PEM type keystores are visible.
* *Truststore* +
From the drop-down list, select a truststore to which to add the TLS context if you are using a truststore to store certificates trusted by the client. Only PEM type truststores are visible.
* *Expiration Date* +
Optionally, select the expiration date for the certificate.
* *ALPN Protocols* +
By default, *H2 - HTTP/1.1* are the selected ALPN protocols. Change this value to support different protocols. 
* *Inbound Settings* +
Optionally, select *Validate Client certificate* to support mTLS for inbound traffic.
* *Outbound Settings* +
Optionally, select *Skip server certificate validation* to skip the validation of the outbound server.

. Optionally, <<select-ciphers, Select Ciphers>> for the TLS context.
+
Cipher selection is not available if only supporting TLS version 1.3.
. Click *Save*.

//end::addContext[]



//tag::redeploy[]

[[redeploy-api-instance]]
== Redeploy an API Instance

If you edit a secret group currently applied to an API Instance, you must individually redeploy all affected instances.

To redeploy an API Instance:

. Go to *Anypoint Platform > API Manager*.
. Click the name of the API Instance to redeploy.
. Click *Runtime & Endpoint Configuration > Save & Apply*.

//end::redeploy[]
